package com.bala.rf_test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RObject implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public RObject() {
    }




}