package com.bala.rf_test;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RObject implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public RObject() {
    }

    private java.lang.String field1;
	private java.lang.Integer field2;

	public java.lang.String getField1() {
		return this.field1;
	}

	public void setField1(java.lang.String field1) {
		this.field1 = field1;
	}

	public java.lang.Integer getField2() {
		return this.field2;
	}

	public void setField2(java.lang.Integer field2) {
		this.field2 = field2;
	}

	public RObject(java.lang.String field1, java.lang.Integer field2) {
		this.field1 = field1;
		this.field2 = field2;
	}



}